site_name: GSAI-study
repo_url: https://github.com/GSAIacademic/GSAI-study
repo_name: GSAIacademic/GSAI-study
edit_uri: edit/main/docs/
site_url: https://gsaiacademic.github.io/GSAI-study/

theme:
  name: material
  language: zh
  features:
    - navigation.tabs
    - navigation.top
    - search.highlight
    - header.autohide
    - navigation.tracking
    - content.action.edit
    - navigation.instant
    - navigation.indexes
    - navigation.collapse
    - toc.follow
    - toc.integrate
    - search.suggest
    - search.share
  palette:
    primary: blue
    accent: orange
  font:
    text: Roboto
    code: Roboto Mono
  icon:
    repo: fontawesome/brands/github

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - attr_list
  - md_in_html
  - def_list
  - footnotes
  - tables
  - pymdownx.emoji

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

plugins:
  - search:
      lang: zh
      prebuild_index: true  # 预构建搜索索引
  - minify:
      minify_html: true
      minify_js: true
      minify_css: true
      htmlmin_opts:
          remove_comments: true
  - exclude:
      glob:
        - "*.tmp"
        - "*.pdf"
        - "*.ppt"
        - "*.doc"
        - "*.docx"
        - "node_modules/*"
        - "site/*"
      regex:
        - '.*\.(tmp|pdf|ppt|doc|docx)$'
  # 添加缓存插件
  - offline

copyright: Copyright &copy; 2024 GSAI-study

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/GSAIacademic/GSAI-study
  generator: false
  version:
    provider: mike
    default: latest

# nav 部分将由脚本自动生成
