site_name: GSAI-study
repo_url: https://github.com/GSAIacademic/GSAI-study
repo_name: GSAIacademic/GSAI-study
edit_uri: edit/main/docs/
site_url: https://gsaiacademic.github.io/GSAI-study/

theme:
  name: material
  language: zh
  features:
    - navigation.tabs      # 保留顶部标签导航
    - navigation.top
    - search.highlight
    - header.autohide
    - navigation.tracking
    - content.action.edit
    - navigation.instant
    - navigation.indexes
    # - navigation.sections  # 移除这个，减少分段
    # - navigation.expand    # 移除这个，默认折叠
    - navigation.collapse   # 添加这个，允许折叠
    - toc.follow           # 添加这个，目录跟随滚动
    - toc.integrate        # 添加这个，将目录集成到左侧导航
    - search.suggest
    - search.share
  palette:
    primary: blue
    accent: orange
  font:
    text: Roboto
    code: Roboto Mono
  icon:
    repo: fontawesome/brands/github

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.arithmatex:
      generic: true
  - attr_list          # 添加属性列表
  - md_in_html        # HTML 中写 Markdown
  - def_list          # 定义列表
  - footnotes         # 脚注
  - tables            # 表格增强
  - pymdownx.emoji:   # 表情支持
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

plugins:
  - search:
      lang: zh
  - minify:
      minify_html: true
      minify_js: true
      minify_css: true
      htmlmin_opts:
          remove_comments: true

copyright: Copyright &copy; 2024 GSAI-study  # 添加版权信息

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/GSAIacademic/GSAI-study
  
  # 添加以下配置
  generator: false  # 不显示 "Made with Material for MkDocs" 
  version:
    provider: mike  # 使用 mike 进行版本控制
    default: latest # 默认显示最新版本
