name: Deploy MkDocs
on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      # pip 缓存可以避免每次都重新下载相同的包
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
          cache: 'pip'  # 缓存 pip 依赖
      
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install mkdocs-exclude  # 直接安装 exclude 插件
      
      - name: Sync files to docs
        run: |
          rm -rf docs
          mkdir -p docs
          
          # 创建样式目录并写入 CSS
          mkdir -p docs/stylesheets
          cat > docs/stylesheets/extra.css << 'EOL'
          /* PDF 容器样式 */
          .pdf-container {
              width: 100%;
              margin: 20px 0;
              border: 1px solid #ddd;
              border-radius: 4px;
              overflow: hidden;
          }
          .pdf-container embed,
          .pdf-container object {
              width: 100%;
              height: 600px;
              border: none;
          }
          @media screen and (max-width: 768px) {
              .pdf-container embed,
              .pdf-container object {
                  height: 400px;
              }
          }
          EOL
          
          # 使用 rsync 来复制文件，确保包含 PDF
          for dir in "大一课程" "大二课程" "大三和大四课程"; do
            if [ -d "$dir" ]; then
              echo "Copying $dir to docs/$dir"
              rsync -av --progress "$dir" "docs/" --include="*.pdf" --include="*/"
            fi
          done
          
          cp "README.md" "docs/index.md"
          cp "start.md" "docs/"
      
      - name: Generate Navigation
        run: |
          python scripts/generate_nav.py
      
      - name: Clean and Deploy
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          mkdocs gh-deploy --force --clean --verbose
