name: Deploy MkDocs
on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 10  # 添加超时限制
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      # pip 缓存可以避免每次都重新下载相同的包
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
          cache: 'pip'  # 缓存 pip 依赖
      
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install mkdocs-exclude  # 直接安装 exclude 插件
      
      - name: Sync files to docs
        run: |
          # 添加文件大小检查
          echo "Checking file sizes..."
          find . -type f -size +10M -exec ls -lh {} \;
          
          # 创建样式目录并写入 CSS
          mkdir -p docs/stylesheets
          cat > docs/stylesheets/extra.css << 'EOL'
          /* PDF 容器样式 */
          .pdf-container {
              width: 100%;
              margin: 20px 0;
              border: 1px solid #ddd;
              border-radius: 4px;
              overflow: hidden;
          }
          .pdf-container embed,
          .pdf-container object {
              width: 100%;
              height: 600px;
              border: none;
          }
          @media screen and (max-width: 768px) {
              .pdf-container embed,
              .pdf-container object {
                  height: 400px;
              }
          }
          EOL
          
          # 复制所有文件，包括 PDF
          for dir in "大一课程" "大二课程" "大三和大四课程"; do
            if [ -d "$dir" ]; then
              echo "Copying $dir to docs/$dir"
              mkdir -p "docs/$dir"
              cp -r "$dir"/* "docs/$dir/"
            fi
          done
          
          cp "README.md" "docs/index.md"
          cp "start.md" "docs/"
      
      - name: Generate Navigation
        run: |
          python scripts/generate_nav.py
      
      - name: Clean and Deploy
        run: |
          # 清理之前的构建
          rm -rf site/
          
          # 使用 --dirty 选项加快部署
          mkdocs gh-deploy --force --dirty --verbose
