name: Deploy MkDocs
on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      # 添加 Python 缓存
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
          cache: 'pip'
      
      # 添加依赖缓存
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      
      - name: Install dependencies
        run: |
          pip install mkdocs-material mkdocs-minify-plugin pyyaml pymdown-extensions
      
      # 添加构建缓存
      - name: Cache build
        uses: actions/cache@v3
        with:
          path: site
          key: mkdocs-build-${{ github.sha }}
          restore-keys: |
            mkdocs-build-
      
      - name: Sync files to docs
        run: |
          rm -rf docs
          mkdir -p docs
          
          # 使用 rsync 替代 cp，可以更快地复制文件
          for dir in "大一课程" "大二课程" "大三和大四课程"; do
            if [ -d "$dir" ]; then
              echo "Copying $dir to docs/$dir"
              rsync -av --progress "$dir" "docs/"
            fi
          done
          
          cp "README.md" "docs/index.md"
          cp "start.md" "docs/"
      
      - name: Generate Navigation
        run: |
          python scripts/generate_nav.py
      
      - name: Clean and Deploy
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          mkdocs gh-deploy --force --clean --verbose
